# Generated by Django 5.2.7 on 2025-11-19 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat_message_chatparticipant_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_1_symbol', models.CharField(choices=[('X', 'X'), ('O', 'O')], max_length=5)),
                ('player_2_symbol', models.CharField(choices=[('X', 'X'), ('O', 'O')], max_length=5)),
                ('field_1', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_2', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_3', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_4', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_5', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_6', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_7', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_8', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('field_9', models.CharField(choices=[('EMPTY', 'Empty'), ('X', 'X'), ('O', 'O')], default='EMPTY', max_length=5)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_turn', models.ForeignKey(db_column='current_turn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_current_turn', to='api.user')),
                ('player_1_id', models.ForeignKey(db_column='player_1_id', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_1', to='api.user')),
                ('player_2_id', models.ForeignKey(db_column='player_2_id', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_player_2', to='api.user')),
                ('winner', models.ForeignKey(blank=True, db_column='winner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='api.user')),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
